ethereum:
  default_network: local-docker

  local-docker:
    default_provider: rpc
    settings:
      url: http://anvil:8545
      chain_id: 1

contracts_folder: src/cork_sim/contracts

dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.9.2

solidity:
  import_remapping:
    - '@openzeppelin/contracts/=src/cork_sim/contracts/.cache/openzeppelin/4.9.2/contracts/'
