services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    # pass in your MAINNET_RPC (e.g. Alchemy/Infura URL)
    environment:
      - MAINNET_RPC=${MAINNET_RPC}
      - FORK_BLOCK=${FORK_BLOCK}
      - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
    # mount your code for live edits
    volumes:
      - ./:/app:cached
    # map Anvil port out so you can also point Ape at http://localhost:8545 if you like
    ports:
      - "8545:8545"
    # keep stdin/tty so you can "docker-compose exec dev bash"
    stdin_open: true
    tty: true
